version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: portaluser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: employeedb
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    expose:
      - "5000"  # internal only, not exposed to host
    environment:
      DATABASE_URL: postgresql://portaluser:securepassword@db:5432/employeedb
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend

volumes:
  db-data:

